# Generated by Django 5.2.6 on 2025-09-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='home_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='social_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(1, 'Por Hacer'), (2, 'En Progreso'), (3, 'Hecho')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='university_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='work_tag',
            field=models.BooleanField(default=False),
        ),
    ]
