# Generated by Django 5.2.5 on 2025-09-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_home_tag_task_priority_task_social_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
